Homework1
made-ml-in-prod-2022/alexysxeightn pull request #1
Opened 2022-05-09 09:03 UTC by alexysxeightn

### Архитектурные и тактические решения:

- Созданы конфигурации для обучения логистической регрессии и случайного леса.
- Созданы тождественный и OneHot трансформеры.
- Созданы функции для генерации синтетических данных, но не были написаны тесты (не успел по времени, TDD-фанаты меня убьют). Данные генерируются равномерно в диапазоне между минимальным и максимальным значением данной фичи. Стратегия генерации разная для категориальных, непрерывных и дискретных величин.
- Отчет по анализу данных генерируется автоматически, используя `pandas-profiling`.
- Для конфигурирования использовалась `hydra`.
- Для сущностей из конфигов были написаны датаклассы (содержатся в файлах вида `*_params.py`).
- Не подключал хранилище для данных (данные хранятся в самом проекте в `data/raw`).
- Вывод логов, данных гидры, pickle-файлов моделей и json-файлов с метриками осуществляется в папку `artifacts`.

### Самооценка

0. В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. (1/1)
1. В пулл-реквесте проведена самооценка (1/1)
2. Выполнено EDA с использованием скрипта. (2/2)
3. Написана функция/класс для тренировки модели, вызов оформлен как утилита командной строки, записана в readme инструкция по запуску (3/3)
4. Написана функция/класс predict (вызов оформлен как утилита командной строки), которая примет на вход артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по вызову записана в readme (3/3)
5. Проект имеет модульную структуру. (2/2)
6. Использованы логгеры (2/2)
7. Написаны тесты на отдельные модули и на прогон обучения и predict. (0/3)
8. Для тестов генерируются синтетические данные, приближенные к реальным. (2/2)
9. Обучение модели конфигурируется с помощью конфигов yaml. (3/3) 
10. Используются датаклассы для сущностей из конфига, а не голые dict (2/2)
11. Напишите кастомный трансформер и протестируйте его (2/3) (трансформеры написаны, а тестов нет)
12. В проекте зафиксированы все зависимости (1/1)
13. Настроен CI для прогона тестов, линтера на основе github actions (3/3).

Дополнительные баллы:
- Используйте hydra для конфигурирования (3/3)
- Mlflow не использовал (0/6)

2022-05-12 03:39 UTC, alexysxeightn commented
Суммарные баллы: 30/40

2022-05-25 13:32 UTC, SVizor42 commented on ml_project/visualize.py
> +import os
Не используется

2022-05-25 13:33 UTC, SVizor42 commented on ml_project/visualize.py
> +from src.train_pipeline_params import get_training_pipeline_params, TrainingPipelineParams
Нужно разделить стандартные и локальные импорты

2022-05-25 13:33 UTC, SVizor42 commented on ml_project/src/utils.py
> +from typing import Union
Не используется

2022-05-25 14:21 UTC, SVizor42 commented on ml_project/src/train_pipeline.py
> +        metric_scores[metric_name] = score_func(target_predicted, target_val)
Тут вроде ROC-AUC проскорится не по вероятностям. Не критично, просто для понимания :)

2022-05-25 14:30 UTC, SVizor42 commented on ml_project/src/train_pipeline.py
> +        pickle_object(transformer, pipeline_params.output_transformer_path)
Для инфо: можно было сразу пайплайн собрать и сохранить

2022-05-25 14:46 UTC, SVizor42 requested changes
В целом, проект хороший. Мне понравился, жаль не успел тесты добавить.
Еще почему-то не нашел CI workflow.

Пару комментариев:
1. В некоторых местах не хватает docstrings (не критично)
2. Еще раз прогнать код через flake или другой линтер (желательно поправить)

2022-06-11 21:14 UTC, SVizor42 approved these changes
На комментарии не получил ответов. CI мне так и не удалось найти, поэтому -3 балла. Ветку можно сливать.

**Сумма: 27 баллов**

2022-06-12 00:55 UTC, merged